### ISSUE TITLE
RFC - Implemenatation ideas

### ISSUE THREAD

**Issue by liuggio** [perftools/xhgui#16]
Hi,
I like your project and we are using in production,
some ideas...
- Writer(external) and reader(web) should not share the same config file, they are  conceptually different.
- The writer 'd have an interface (maybe doctrine common cache) so swapping with other mechanisms as APC/Redis/MYSQL 'll become easy related to #11 
- `Composer`ize the project vendors
- uses PSR*

what do you think?

**Comment by dennisdegreef** [comment]
I'm working on a library which has multiple datastores, but currently has not 'frontend'. I'm currently refactoring the internal data structure also keeping in mind that XHGui would work on top of the datastore adapter of Mongo. Is there any way we can work together to complete this common goal? A shared interface for datastructures inside of mongo and/or files would be awesome!

My library is link0/profiler and i'm currently working on https://github.com/link0/profiler/pull/62

**Comment by markstory** [comment]
@dennisdegreef I don't see why we couldn't try and share the same mongo data structures. We'll need to figure out a way to make changes in a backwards compatible way on our side though.

**Comment by Krinkle** [comment]
1. [x] The writer have an to swapping with other backends

Done per https://github.com/perftools/xhgui/pull/244. See also #11.

2.[x] Use compsoer for dependencies.

Done.

3. [x] Separate writer and reader config.

Done with <https://github.com/perftools/php-profiler>.

4. Use PSR*.

There will always be another PSR. But overall I don't think this matters much for XHGui since it has almost no dependencies and the ones it does have, I think, don't benefit being able to swap out (they just work),  also since it's not meant to be composed with other apps as library but is itself a finished application.

If this this about autoloading PSR, it uses that now (just PSR0 for now).

If this is about coding style consistency, that isn't done yet. Could set up PHPCS in a separate ticket.  I filed https://github.com/perftools/xhgui/issues/299 for that now.

This ticket can be closed I think?
