### ISSUE TITLE
127.0.0.1:27017: unrecognized field "cursor

### ISSUE THREAD

**Issue by jon-frankel** [perftools/xhgui#269]
When I click on the URL for a run from any page, I get this error:

> ## Aw shoot, Xhgui hit an error
> 127.0.0.1:27017: unrecognized field "cursor
>
> You should check the following things:
> - Ensure that Mongo has been started
> - That config/config.php has the right connection information.
> - That the cache/ directory has the correct permissions.
>
> **Stack Trace**

```
#0 /usr/local/src/xhgui/src/Xhgui/Searcher/Mongo.php(121): MongoCollection->aggregate(Array, Array)
#1 /usr/local/src/xhgui/src/Xhgui/Controller/Run.php(216): Xhgui_Searcher_Mongo->getPercentileForUrl(90, '[/path/to/endpoint/]...', Array)
#2 /usr/local/src/xhgui/src/routes.php(53): Xhgui_Controller_Run->url()
#3 [internal function]: {closure}()
#4 /usr/local/src/xhgui/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#5 /usr/local/src/xhgui/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#6 /usr/local/src/xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 /usr/local/src/xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 /usr/local/src/xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call()
#9 /usr/local/src/xhgui/src/Xhgui/Middleware/Render.php(11): Slim\Middleware\SessionCookie->call()
#10 /usr/local/src/xhgui/vendor/slim/slim/Slim/Slim.php(1300): Xhgui_Middleware_Render->call()
#11 /usr/local/src/xhgui/webroot/index.php(10): Slim\Slim->run()
#12 {main}
```

This happens with any run with any URL. I'm running xhgui through edyan/docker-xhgui with the 5.6 version. The only thing I've customized in the dockerfile is the location of the config script.

Is it missing an index, or not creating fields where it should?

**Comment by Krinkle** [comment]
I'm encountering the same issue on a legacy XHGui install that uses MongoDB 2.4. While EOL, the README specifies compatibility with MongoDB 2.2 and later.

Most everything works fine, including the run lists and run views. The only thing that doesn't work is clicking a url in the index view, which is meant to show a reduced set of profiles that match the same url.

While I don't need this feature to work, the reason people run in to the error very frequently is because most users assume that clicking the url in the table row will lead to viewing that profile.

In actually, the way to view the profile is by clicking the **timestamp**.

(Clicking the url leads to a pre-filled search view instead, which is the part that doesn't work currently.)

**Comment by glensc** [comment]
So, this happens with MongoDB 2.2, and the fix is to use MongoDB 2.4?

**Comment by Krinkle** [comment]
No, the issue happened with MongoDB 2.4 (Debian 8 Jessie).

MongoDB 2.2+ is what the XHGUi docs state as supported.

The issue went away after upgrading to MongoDB 3.2 (Debian 9 Stretch), and at Wikimedia we since migrated our XHGui database to MySQL (MariaDB).

**Comment by glensc** [comment]
I propose just then to update documentation about minimum version, no point putting more effort to this, even mongodb 3.2 is old:
- https://docs.mongodb.com/manual/release-notes/3.2/ "Dec 8, 2015"
