### ISSUE TITLE
redirects after run delete do not honor 'path.prefix'

### ISSUE THREAD

**Issue by dadamssg** [perftools/xhgui#424]
It appears that the `path.prefix` is only honored in the twig templates and not in the redirects from the backend. For example, the `deleteSubmit()` controller action redirects using the following, which simply redirects to the domain root, `/`.

```
$this->app->redirect($this->app->urlFor('home'));
``` 

If i'm hosting xhgui at `https://mydomain.com/tools/xhgui/` and i have `path.prefix` set to `/tools/xhgui/`, after a delete i will be redirected to `https://mydomain.com`

Not a huge bug by any means but a minor annoyance.

**Comment by glensc** [comment]
PR adding the config support:
- https://github.com/perftools/xhgui/pull/298

**Comment by glensc** [comment]
I think it's important how have you setup your webserver, I think your "alias" is set up incorrectly so that xhgui thinks it's installed at "/" while at webserver level it's at "/tools/xhgui".

you need to rewrite the incoming/outgoing requests equally.

In Apache, it's typically `ProxyPassReverse`:
- https://httpd.apache.org/docs/2.4/rewrite/proxy.html

**Comment by dadamssg** [comment]
ah, you may be right. I'm using nginx. i'll need to mess around with my nginx conf file

**Comment by glensc** [comment]
you may be right too, as I added the original change for assets to render properly. but then again, the 'home' route app should detect automatically how the app is installed.

you should post your nginx config here. it maybe something obvious, but otherwise maybe some other community member can have answer if they see the whole picture.

**Comment by glensc** [comment]
No longer an issue after slim upgrade:
- https://github.com/perftools/xhgui/pull/333

In fact that slim added prefix needed to be reversed to prevent double paths:
- https://github.com/perftools/xhgui/pull/455

Re-open (or create new issue) once 0.20.0 is released and this is still an issue (or is new issue).
